apiVersion: apps/v1
kind: Deployment
metadata:
  name: bechmark-beta-api
  namespace: benchmark
  labels:
    app: bechmark-beta-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bechmark-beta-api
  template:
    metadata:
      labels:
        app: bechmark-beta-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000  # Example non-root user ID
      containers:
      - name: bechmark-beta-api
        image: ghcr.io/raffelprama/my-fastapi:0.1.7
        ports:
        - containerPort: 8000  # Port the application listens on
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: bechmark-beta-api-env 
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000  # Example non-root user ID
      imagePullSecrets:
      - name: regcred  # Reference the secret created